-- TASTE_CONFIG 테이블에 RECOMMENDED_PRODUCT_SCORES 컬럼 추가
-- RECOMMENDED_PRODUCTS와 1:1 매핑되는 점수 정보

ALTER TABLE TASTE_CONFIG 
ADD RECOMMENDED_PRODUCT_SCORES CLOB;

COMMENT ON COLUMN TASTE_CONFIG.RECOMMENDED_PRODUCT_SCORES IS '카테고리별 추천 제품 점수 매핑 (JSON 객체, RECOMMENDED_PRODUCTS와 1:1 매핑)';

