-- TASTE_CONFIG 테이블에 ill-suited 및 category별 score 컬럼 추가
-- 
-- 추가되는 컬럼:
-- 1. ILL_SUITED_CATEGORIES: ill-suited 카테고리 리스트 (JSON 배열, CLOB)
-- 2. 각 카테고리별 점수 컬럼: {CATEGORY_NAME}_SCORE (NUMBER(5,2))
--    예: TV_SCORE, 냉장고_SCORE, 에어컨_SCORE 등
--
-- 사용법:
-- 1. 이 SQL 스크립트를 실행하여 컬럼 추가
-- 2. 동적 카테고리 컬럼은 필요에 따라 추가 (또는 JSON으로 관리)

-- 1. ILL_SUITED_CATEGORIES 컬럼 추가
ALTER TABLE TASTE_CONFIG 
ADD ILL_SUITED_CATEGORIES CLOB;

-- 2. 주요 카테고리별 점수 컬럼 추가 (0~100점)
-- Oracle은 컬럼명이 30자 제한이 있으므로 주의

-- TV 관련
ALTER TABLE TASTE_CONFIG 
ADD TV_SCORE NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "프로젝터_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "스탠바이미_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "오디오_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "사운드바_SCORE" NUMBER(5,2);

-- 냉장고 관련
ALTER TABLE TASTE_CONFIG 
ADD "냉장고_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "김치냉장고_SCORE" NUMBER(5,2);

-- 세탁 관련
ALTER TABLE TASTE_CONFIG 
ADD "세탁기_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "건조기_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "워시타워_SCORE" NUMBER(5,2);

-- 주방 가전
ALTER TABLE TASTE_CONFIG 
ADD "식기세척기_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "전자레인지_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "오븐_SCORE" NUMBER(5,2);

-- 공기 관련
ALTER TABLE TASTE_CONFIG 
ADD "에어컨_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "공기청정기_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "가습기_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "제습기_SCORE" NUMBER(5,2);

-- 청소 관련
ALTER TABLE TASTE_CONFIG 
ADD "청소기_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "로봇청소기_SCORE" NUMBER(5,2);

-- 기타
ALTER TABLE TASTE_CONFIG 
ADD "정수기_SCORE" NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD "와인셀러_SCORE" NUMBER(5,2);

-- AIHome, OBJET, SIGNATURE 등 (컬럼명이 짧아야 함)
ALTER TABLE TASTE_CONFIG 
ADD AIHOME_SCORE NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD OBJET_SCORE NUMBER(5,2);

ALTER TABLE TASTE_CONFIG 
ADD SIGNATURE_SCORE NUMBER(5,2);

-- 컬럼 주석 추가 (모든 컬럼 추가 후 실행)
-- 주석은 선택사항이므로 오류 발생 시 무시해도 됨
BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TASTE_CONFIG.ILL_SUITED_CATEGORIES IS ''온보딩 답변과 완전히 부적합한 카테고리 리스트 (JSON 배열)''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TASTE_CONFIG.TV_SCORE IS ''TV 카테고리 점수 (0~100점)''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TASTE_CONFIG."냉장고_SCORE" IS ''냉장고 카테고리 점수 (0~100점)''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TASTE_CONFIG."세탁기_SCORE" IS ''세탁기 카테고리 점수 (0~100점)''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TASTE_CONFIG."에어컨_SCORE" IS ''에어컨 카테고리 점수 (0~100점)''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TASTE_CONFIG."공기청정기_SCORE" IS ''공기청정기 카테고리 점수 (0~100점)''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TASTE_CONFIG."청소기_SCORE" IS ''청소기 카테고리 점수 (0~100점)''';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- 주석 추가 실패 시 무시
END;
/

-- 참고: 동적으로 카테고리를 추가해야 하는 경우,
-- 추가 컬럼을 생성하거나 CATEGORY_SCORES JSON 컬럼을 사용할 수 있습니다.

