-- 남은 한글 컬럼명 추가 (큰따옴표 사용)
ALTER TABLE TASTE_CONFIG ADD "냉장고_SCORE" NUMBER(5,2);
ALTER TABLE TASTE_CONFIG ADD "세탁기_SCORE" NUMBER(5,2);
ALTER TABLE TASTE_CONFIG ADD "에어컨_SCORE" NUMBER(5,2);
ALTER TABLE TASTE_CONFIG ADD "청소기_SCORE" NUMBER(5,2);

-- ILL_SUITED_CATEGORIES 컬럼 확인 및 추가
ALTER TABLE TASTE_CONFIG ADD ILL_SUITED_CATEGORIES CLOB;



