-- ============================================================
-- WISHLIST 테이블 생성
-- 위시리스트 기능을 위한 테이블
-- ============================================================

CREATE TABLE WISHLIST (
    WISHLIST_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(100) NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_WISHLIST_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT UK_WISHLIST_USER_PRODUCT UNIQUE (USER_ID, PRODUCT_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_WISHLIST
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 인덱스 생성
CREATE INDEX IDX_WISHLIST_USER_ID ON WISHLIST(USER_ID);
CREATE INDEX IDX_WISHLIST_PRODUCT_ID ON WISHLIST(PRODUCT_ID);
CREATE INDEX IDX_WISHLIST_CREATED_AT ON WISHLIST(CREATED_AT);

-- 주석 추가
COMMENT ON TABLE WISHLIST IS '위시리스트 테이블 (찜하기 기능)';
COMMENT ON COLUMN WISHLIST.WISHLIST_ID IS '위시리스트 ID (PRIMARY KEY)';
COMMENT ON COLUMN WISHLIST.USER_ID IS '사용자 ID (카카오 로그인 연동 시)';
COMMENT ON COLUMN WISHLIST.PRODUCT_ID IS '제품 ID (FK, PRODUCT.PRODUCT_ID 참조)';
COMMENT ON COLUMN WISHLIST.CREATED_AT IS '찜하기 추가 일시 (기본값: SYSDATE)';

COMMIT;

