-- ========================================
-- 온보딩 시스템 리팩토링 마이그레이션 스크립트
-- 실행 전 백업 권장
-- ========================================

-- ========================================
-- 1단계: 중복 테이블 제거
-- ========================================

DROP TABLE ONBOARDING_SESSION_CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE ONBOARDING_SESSION_MAIN_SPACES CASCADE CONSTRAINTS;
DROP TABLE ONBOARDING_SESSION_PRIORITIES CASCADE CONSTRAINTS;
DROP TABLE USER_SAMPLE_PURCHASED_ITEMS CASCADE CONSTRAINTS;
DROP TABLE USER_SAMPLE_RECOMMENDATIONS CASCADE CONSTRAINTS;

-- ========================================
-- 2단계: ONBOARDING_SESSION 테이블 수정
-- ========================================

-- 2.1 불필요한 CLOB 컬럼 제거 (존재하는 경우만)
BEGIN
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ONBOARDING_SESSION DROP COLUMN MAIN_SPACE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ONBOARDING_SESSION DROP COLUMN PRIORITY_LIST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ONBOARDING_SESSION DROP COLUMN SELECTED_CATEGORIES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ONBOARDING_SESSION DROP COLUMN RECOMMENDED_PRODUCTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ONBOARDING_SESSION DROP COLUMN RECOMMENDATION_RESULT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
END;
/

-- 2.2 중복 컬럼 제거 (존재하는 경우만)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ONBOARDING_SESSION DROP COLUMN USER_ID';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -904 THEN RAISE; END IF;
END;
/

-- 2.3 날짜 컬럼명 통일 (CREATED_DATE가 있는 경우만)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ONBOARDING_SESSION RENAME COLUMN CREATED_DATE TO CREATED_AT';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -904 AND SQLCODE != -957 THEN RAISE; END IF;
END;
/

-- 2.4 MEMBER_ID NULL 허용
ALTER TABLE ONBOARDING_SESSION MODIFY MEMBER_ID VARCHAR2(30) NULL;

-- 2.5 MEMBER_ID 기본값 설정 (옵션)
ALTER TABLE ONBOARDING_SESSION MODIFY MEMBER_ID DEFAULT 'GUEST';

-- ========================================
-- 3단계: GUEST 회원 생성
-- ========================================

-- MEMBER 테이블의 날짜 컬럼명을 CREATED_AT으로 통일 시도 (없으면 무시)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MEMBER RENAME COLUMN CREATED_DATE TO CREATED_AT';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 OR SQLCODE = -957 THEN
            NULL;  -- CREATED_DATE가 없거나 이미 CREATED_AT이면 무시
        ELSE
            RAISE;
        END IF;
END;
/

-- GUEST 회원 생성 (CREATED_AT 또는 CREATED_DATE 사용)
DECLARE
    v_col_name VARCHAR2(30);
BEGIN
    -- CREATED_AT 컬럼 존재 확인
    SELECT COUNT(*) INTO v_col_name
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'MEMBER' AND COLUMN_NAME = 'CREATED_AT';
    
    IF v_col_name > 0 THEN
        -- CREATED_AT 사용
        MERGE INTO MEMBER m
        USING (SELECT 'GUEST' AS MEMBER_ID FROM DUAL) src
        ON (m.MEMBER_ID = src.MEMBER_ID)
        WHEN NOT MATCHED THEN
          INSERT (MEMBER_ID, PASSWORD, NAME, CREATED_AT)
          VALUES ('GUEST', 'N/A', 'Guest User', SYSDATE);
    ELSE
        -- CREATED_DATE 사용
        MERGE INTO MEMBER m
        USING (SELECT 'GUEST' AS MEMBER_ID FROM DUAL) src
        ON (m.MEMBER_ID = src.MEMBER_ID)
        WHEN NOT MATCHED THEN
          INSERT (MEMBER_ID, PASSWORD, NAME, CREATED_DATE)
          VALUES ('GUEST', 'N/A', 'Guest User', SYSDATE);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        -- 최소한의 필수 컬럼만 사용
        MERGE INTO MEMBER m
        USING (SELECT 'GUEST' AS MEMBER_ID FROM DUAL) src
        ON (m.MEMBER_ID = src.MEMBER_ID)
        WHEN NOT MATCHED THEN
          INSERT (MEMBER_ID, PASSWORD, NAME)
          VALUES ('GUEST', 'N/A', 'Guest User');
        COMMIT;
END;
/

-- ========================================
-- 4단계: TASTE_CONFIG 테이블 정리
-- ========================================

-- 4.1 개별 카테고리 점수 컬럼 제거 (존재하는 경우만)
BEGIN
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN CATEGORY_SCORES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN TV_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 냉장고_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 세탁기_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 에어컨_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 청소기_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 프로젝터_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 스탠바이미_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 오디오_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 사운드바_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 김치냉장고_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 건조기_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 워시타워_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 전자레인지_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 오븐_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 공기청정기_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 가습기_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 제습기_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 와인셀러_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN OBJET_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN SIGNATURE_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 정수기_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN AIHOME_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG DROP COLUMN 식기세척기_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
END;
/

-- 4.2 날짜 컬럼명 통일 (LAST_SIMULATION_DATE가 있는 경우만)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE TASTE_CONFIG RENAME COLUMN LAST_SIMULATION_DATE TO LAST_SIMULATION_AT';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -904 AND SQLCODE != -957 THEN RAISE; END IF;
END;
/

-- ========================================
-- 5단계: 신규 테이블 생성
-- ========================================

-- 5.1 STYLE_MESSAGE 테이블 (Oracle 11g 호환)
-- 시퀀스 생성
BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_STYLE_MESSAGE
        START WITH 1
        INCREMENT BY 1
        NOCACHE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;  -- 이미 존재하면 무시
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE STYLE_MESSAGE (
        MESSAGE_ID NUMBER PRIMARY KEY,
        VIBE VARCHAR2(20) NOT NULL,
        HOUSEHOLD_SIZE NUMBER(1),
        BUDGET_LEVEL VARCHAR2(20),
        TITLE_TEXT VARCHAR2(500) NOT NULL,
        SUBTITLE_TEXT VARCHAR2(1000) NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
        IS_ACTIVE CHAR(1) DEFAULT ''Y'',
        CONSTRAINT CHK_STYLE_MESSAGE_VIBE 
            CHECK (VIBE IN (''modern'', ''cozy'', ''pop'', ''luxury'')),
        CONSTRAINT CHK_STYLE_MESSAGE_BUDGET 
            CHECK (BUDGET_LEVEL IN (''budget'', ''standard'', ''premium'', ''luxury'')),
        CONSTRAINT CHK_STYLE_MESSAGE_ACTIVE
            CHECK (IS_ACTIVE IN (''Y'', ''N''))
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;  -- 이미 존재하면 무시
END;
/

-- 트리거 생성 (자동 ID 생성)
CREATE OR REPLACE TRIGGER TRG_STYLE_MESSAGE_ID
    BEFORE INSERT ON STYLE_MESSAGE
    FOR EACH ROW
BEGIN
    IF :NEW.MESSAGE_ID IS NULL THEN
        SELECT SEQ_STYLE_MESSAGE.NEXTVAL INTO :NEW.MESSAGE_ID FROM DUAL;
    END IF;
END;
/

BEGIN
    BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STYLE_MESSAGE_VIBE ON STYLE_MESSAGE(VIBE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STYLE_MESSAGE_SIZE ON STYLE_MESSAGE(HOUSEHOLD_SIZE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
END;
/

COMMENT ON TABLE STYLE_MESSAGE IS '포트폴리오 결과 화면의 스타일 분석 메시지 관리';
COMMENT ON COLUMN STYLE_MESSAGE.VIBE IS '인테리어 무드: modern/cozy/pop/luxury';
COMMENT ON COLUMN STYLE_MESSAGE.TITLE_TEXT IS '스타일 분석 타이틀 (예: "모던 & 미니멀한 당신에게 어울리는 LG 오브제 스타일")';
COMMENT ON COLUMN STYLE_MESSAGE.SUBTITLE_TEXT IS '스타일 분석 설명 (예: "당신의 공간 분위기와 요리 중심 라이프스타일을 반영해...")';

-- 5.2 SHARE_LINK 테이블 (이미 존재하면 무시)
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE SHARE_LINK (
        LINK_ID VARCHAR2(50) PRIMARY KEY,
        PORTFOLIO_ID NUMBER NOT NULL,
        SHARE_TYPE VARCHAR2(20) NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        EXPIRES_AT DATE,
        ACCESS_COUNT NUMBER DEFAULT 0,
        CONSTRAINT FK_SHARE_PORTFOLIO 
            FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO_SESSION(PORTFOLIO_ID),
        CONSTRAINT CHK_SHARE_TYPE
            CHECK (SHARE_TYPE IN (''kakao'', ''link''))
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;  -- 이미 존재하면 무시
END;
/

BEGIN
    BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SHARE_LINK_PORTFOLIO ON SHARE_LINK(PORTFOLIO_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SHARE_LINK_CREATED ON SHARE_LINK(CREATED_AT)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
END;
/

COMMENT ON TABLE SHARE_LINK IS '포트폴리오 외부 공유 링크 관리';
COMMENT ON COLUMN SHARE_LINK.LINK_ID IS '공유 링크 고유 ID (UUID)';
COMMENT ON COLUMN SHARE_LINK.SHARE_TYPE IS '공유 타입: kakao(카카오톡) / link(링크 복사)';

-- 5.3 PORTFOLIO_VERSION 테이블 (Oracle 11g 호환)
-- 시퀀스 생성
BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PORTFOLIO_VERSION
        START WITH 1
        INCREMENT BY 1
        NOCACHE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;  -- 이미 존재하면 무시
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE PORTFOLIO_VERSION (
        VERSION_ID NUMBER PRIMARY KEY,
        PORTFOLIO_ID NUMBER NOT NULL,
        VERSION_NUMBER NUMBER NOT NULL,
        CHANGE_TYPE VARCHAR2(20) NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT FK_PORTFOLIO_VERSION 
            FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO_SESSION(PORTFOLIO_ID),
        CONSTRAINT CHK_VERSION_CHANGE_TYPE
            CHECK (CHANGE_TYPE IN (''refresh'', ''manual_edit'')),
        CONSTRAINT UK_PORTFOLIO_VERSION
            UNIQUE (PORTFOLIO_ID, VERSION_NUMBER)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;  -- 이미 존재하면 무시
END;
/

-- 트리거 생성 (자동 ID 생성)
CREATE OR REPLACE TRIGGER TRG_PORTFOLIO_VERSION_ID
    BEFORE INSERT ON PORTFOLIO_VERSION
    FOR EACH ROW
BEGIN
    IF :NEW.VERSION_ID IS NULL THEN
        SELECT SEQ_PORTFOLIO_VERSION.NEXTVAL INTO :NEW.VERSION_ID FROM DUAL;
    END IF;
END;
/

BEGIN
    BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PORTFOLIO_VERSION_ID ON PORTFOLIO_VERSION(PORTFOLIO_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
END;
/

COMMENT ON TABLE PORTFOLIO_VERSION IS '포트폴리오 버전 이력 관리 (다시 추천받기 기능)';
COMMENT ON COLUMN PORTFOLIO_VERSION.CHANGE_TYPE IS '변경 유형: refresh(다시 추천받기) / manual_edit(수동 편집)';

-- ========================================
-- 6단계: 기타 테이블 날짜 컬럼 통일 (CREATED_DATE가 있는 경우만)
-- ========================================

BEGIN
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ONBOARDING_ANSWER RENAME COLUMN CREATED_DATE TO CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 AND SQLCODE != -957 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ONBOARDING_QUESTION RENAME COLUMN CREATED_DATE TO CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 AND SQLCODE != -957 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ONBOARDING_USER_RESPONSE RENAME COLUMN CREATED_DATE TO CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 AND SQLCODE != -957 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT RENAME COLUMN CREATED_DATE TO CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 AND SQLCODE != -957 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CART RENAME COLUMN CREATED_DATE TO CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 AND SQLCODE != -957 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CONSULTATION RENAME COLUMN CREATED_DATE TO CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 AND SQLCODE != -957 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ESTIMATE RENAME COLUMN CREATED_DATE TO CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 AND SQLCODE != -957 THEN RAISE; END IF; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_SESSION RENAME COLUMN CREATED_DATE TO CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 AND SQLCODE != -957 THEN RAISE; END IF; END;
END;
/

-- ========================================
-- 7단계: 검증 쿼리
-- ========================================

-- 7.1 테이블 존재 확인
SELECT TABLE_NAME 
FROM USER_TABLES 
WHERE TABLE_NAME IN (
    'ONBOARDING_SESSION',
    'ONBOARD_SESS_MAIN_SPACES',
    'ONBOARD_SESS_PRIORITIES',
    'ONBOARD_SESS_CATEGORIES',
    'ONBOARD_SESS_REC_PRODUCTS',
    'STYLE_MESSAGE',
    'SHARE_LINK',
    'PORTFOLIO_VERSION',
    'TASTE_CONFIG',
    'TASTE_CATEGORY_SCORES',
    'TASTE_RECOMMENDED_PRODUCTS'
)
ORDER BY TABLE_NAME;

-- 7.2 ONBOARDING_SESSION 구조 확인
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'ONBOARDING_SESSION'
ORDER BY COLUMN_ID;

-- 7.3 GUEST 회원 존재 확인
SELECT * FROM MEMBER WHERE MEMBER_ID = 'GUEST';

-- 7.4 외래키 제약조건 확인
SELECT 
    c.constraint_name,
    c.table_name,
    cc.column_name,
    c.r_constraint_name,
    r.table_name AS ref_table
FROM user_constraints c
JOIN user_cons_columns cc ON c.constraint_name = cc.constraint_name
LEFT JOIN user_constraints r ON c.r_constraint_name = r.constraint_name
WHERE c.constraint_type = 'R'
AND c.table_name = 'ONBOARDING_SESSION';

COMMIT;

