-- ============================================================
-- ONBOARDING_SESSION 정규화 마이그레이션 스크립트
-- ============================================================
-- 이 스크립트는 ONBOARDING_SESSION 테이블의 CLOB 컬럼들을
-- 정규화된 테이블로 분리합니다.
-- ============================================================

-- ============================================================
-- Step 1: 새 테이블 생성
-- ============================================================

-- 1.1 ONBOARDING_SESSION_MAIN_SPACES 테이블 생성
CREATE TABLE ONBOARDING_SESSION_MAIN_SPACES (
    SESSION_ID VARCHAR2(100) NOT NULL,
    MAIN_SPACE VARCHAR2(50) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    PRIMARY KEY (SESSION_ID, MAIN_SPACE),
    FOREIGN KEY (SESSION_ID) REFERENCES ONBOARDING_SESSION(SESSION_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_SESSION_MAIN_SPACES_SESSION ON ONBOARDING_SESSION_MAIN_SPACES(SESSION_ID);
CREATE INDEX IDX_SESSION_MAIN_SPACES_SPACE ON ONBOARDING_SESSION_MAIN_SPACES(MAIN_SPACE);

COMMENT ON TABLE ONBOARDING_SESSION_MAIN_SPACES IS '온보딩 세션별 주요 공간 정보 (정규화)';
COMMENT ON COLUMN ONBOARDING_SESSION_MAIN_SPACES.SESSION_ID IS '세션 ID (FK)';
COMMENT ON COLUMN ONBOARDING_SESSION_MAIN_SPACES.MAIN_SPACE IS '주요 공간 (living/kitchen/bedroom/dressing/study/all)';
COMMENT ON COLUMN ONBOARDING_SESSION_MAIN_SPACES.CREATED_AT IS '생성 일시';

-- 1.2 ONBOARDING_SESSION_PRIORITIES 테이블 생성
CREATE TABLE ONBOARDING_SESSION_PRIORITIES (
    SESSION_ID VARCHAR2(100) NOT NULL,
    PRIORITY VARCHAR2(20) NOT NULL,
    PRIORITY_ORDER NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    PRIMARY KEY (SESSION_ID, PRIORITY_ORDER),
    FOREIGN KEY (SESSION_ID) REFERENCES ONBOARDING_SESSION(SESSION_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_SESSION_PRIORITIES_SESSION ON ONBOARDING_SESSION_PRIORITIES(SESSION_ID);
CREATE INDEX IDX_SESSION_PRIORITIES_PRIORITY ON ONBOARDING_SESSION_PRIORITIES(PRIORITY);

COMMENT ON TABLE ONBOARDING_SESSION_PRIORITIES IS '온보딩 세션별 우선순위 목록 (정규화)';
COMMENT ON COLUMN ONBOARDING_SESSION_PRIORITIES.SESSION_ID IS '세션 ID (FK)';
COMMENT ON COLUMN ONBOARDING_SESSION_PRIORITIES.PRIORITY IS '우선순위 (design/tech/eco/value)';
COMMENT ON COLUMN ONBOARDING_SESSION_PRIORITIES.PRIORITY_ORDER IS '우선순위 순서 (1, 2, 3...)';
COMMENT ON COLUMN ONBOARDING_SESSION_PRIORITIES.CREATED_AT IS '생성 일시';

-- 1.3 ONBOARDING_SESSION_CATEGORIES 테이블 생성
CREATE TABLE ONBOARDING_SESSION_CATEGORIES (
    SESSION_ID VARCHAR2(100) NOT NULL,
    CATEGORY_NAME VARCHAR2(50) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    PRIMARY KEY (SESSION_ID, CATEGORY_NAME),
    FOREIGN KEY (SESSION_ID) REFERENCES ONBOARDING_SESSION(SESSION_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_SESSION_CATEGORIES_SESSION ON ONBOARDING_SESSION_CATEGORIES(SESSION_ID);
CREATE INDEX IDX_SESSION_CATEGORIES_CATEGORY ON ONBOARDING_SESSION_CATEGORIES(CATEGORY_NAME);

COMMENT ON TABLE ONBOARDING_SESSION_CATEGORIES IS '온보딩 세션별 선택한 카테고리 (정규화)';
COMMENT ON COLUMN ONBOARDING_SESSION_CATEGORIES.SESSION_ID IS '세션 ID (FK)';
COMMENT ON COLUMN ONBOARDING_SESSION_CATEGORIES.CATEGORY_NAME IS '카테고리명 (예: "TV", "냉장고")';
COMMENT ON COLUMN ONBOARDING_SESSION_CATEGORIES.CREATED_AT IS '생성 일시';

-- 1.4 ONBOARDING_SESSION_RECOMMENDED_PRODUCTS 테이블 생성
CREATE TABLE ONBOARDING_SESSION_RECOMMENDED_PRODUCTS (
    SESSION_ID VARCHAR2(100) NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    CATEGORY_NAME VARCHAR2(50),
    RANK_ORDER NUMBER,
    SCORE NUMBER(5,2),
    CREATED_AT DATE DEFAULT SYSDATE,
    PRIMARY KEY (SESSION_ID, PRODUCT_ID),
    FOREIGN KEY (SESSION_ID) REFERENCES ONBOARDING_SESSION(SESSION_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_SESSION_REC_PROD_SESSION ON ONBOARDING_SESSION_RECOMMENDED_PRODUCTS(SESSION_ID);
CREATE INDEX IDX_SESSION_REC_PROD_CATEGORY ON ONBOARDING_SESSION_RECOMMENDED_PRODUCTS(CATEGORY_NAME);

COMMENT ON TABLE ONBOARDING_SESSION_RECOMMENDED_PRODUCTS IS '온보딩 세션별 추천 제품 (정규화)';
COMMENT ON COLUMN ONBOARDING_SESSION_RECOMMENDED_PRODUCTS.SESSION_ID IS '세션 ID (FK)';
COMMENT ON COLUMN ONBOARDING_SESSION_RECOMMENDED_PRODUCTS.PRODUCT_ID IS '제품 ID';
COMMENT ON COLUMN ONBOARDING_SESSION_RECOMMENDED_PRODUCTS.CATEGORY_NAME IS '카테고리명';
COMMENT ON COLUMN ONBOARDING_SESSION_RECOMMENDED_PRODUCTS.RANK_ORDER IS '순위';
COMMENT ON COLUMN ONBOARDING_SESSION_RECOMMENDED_PRODUCTS.SCORE IS '점수 (0~100점)';
COMMENT ON COLUMN ONBOARDING_SESSION_RECOMMENDED_PRODUCTS.CREATED_AT IS '생성 일시';

-- ============================================================
-- Step 2: 데이터 마이그레이션
-- ============================================================
-- 주의: 이 스크립트는 Oracle 11g에서 JSON 함수가 제한적이므로
-- Python 스크립트로 마이그레이션하는 것을 권장합니다.
-- ============================================================

-- 데이터 마이그레이션은 Python 스크립트로 수행
-- api/management/commands/migrate_onboarding_session_to_normalized.py 참고

-- ============================================================
-- Step 3: 기존 컬럼 제거 (선택사항, 마이그레이션 완료 후)
-- ============================================================
-- 주의: 모든 코드가 새 구조를 사용하는지 확인 후 실행
-- ============================================================

-- ALTER TABLE ONBOARDING_SESSION DROP COLUMN MAIN_SPACE;
-- ALTER TABLE ONBOARDING_SESSION DROP COLUMN PRIORITY_LIST;
-- ALTER TABLE ONBOARDING_SESSION DROP COLUMN SELECTED_CATEGORIES;
-- ALTER TABLE ONBOARDING_SESSION DROP COLUMN RECOMMENDED_PRODUCTS;
-- ALTER TABLE ONBOARDING_SESSION DROP COLUMN RECOMMENDATION_RESULT;

-- ============================================================
-- 롤백 스크립트 (필요시)
-- ============================================================

-- DROP TABLE ONBOARDING_SESSION_RECOMMENDED_PRODUCTS;
-- DROP TABLE ONBOARDING_SESSION_CATEGORIES;
-- DROP TABLE ONBOARDING_SESSION_PRIORITIES;
-- DROP TABLE ONBOARDING_SESSION_MAIN_SPACES;


