-- ============================================================
-- 온보딩 관련 테이블 DDL
-- Oracle 11g 호환
-- ============================================================

-- 1. ONBOARDING_QUESTION: 온보딩 질문 항목
CREATE TABLE ONBOARDING_QUESTION (
    QUESTION_ID NUMBER PRIMARY KEY,
    STEP_NUMBER NUMBER NOT NULL,  -- 단계 번호 (1~6)
    QUESTION_TYPE VARCHAR2(50),   -- 질문 유형 (vibe, mate, housing_type, cooking, laundry, media, priority, budget)
    QUESTION_TEXT VARCHAR2(500) NOT NULL,  -- 질문 텍스트
    QUESTION_ORDER NUMBER,  -- 질문 순서 (같은 단계 내에서)
    IS_REQUIRED CHAR(1) DEFAULT 'Y',  -- 필수 여부 (Y/N)
    CONDITION_TYPE VARCHAR2(100),  -- 조건부 질문 타입 (예: kitchen_selected, dressing_selected)
    CONDITION_VALUE VARCHAR2(200),  -- 조건 값
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_ONBOARDING_QUESTION
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 2. ONBOARDING_ANSWER: 온보딩 선택지 항목
CREATE TABLE ONBOARDING_ANSWER (
    ANSWER_ID NUMBER PRIMARY KEY,
    QUESTION_ID NUMBER NOT NULL,  -- ONBOARDING_QUESTION 참조
    ANSWER_VALUE VARCHAR2(100) NOT NULL,  -- 선택지 값 (예: modern, alone, apartment)
    ANSWER_TEXT VARCHAR2(500) NOT NULL,  -- 선택지 텍스트 (예: "모던 & 미니멀", "나 혼자 산다")
    ANSWER_ORDER NUMBER,  -- 선택지 순서
    IMAGE_URL VARCHAR2(500),  -- 이미지 URL (있는 경우)
    IS_ACTIVE CHAR(1) DEFAULT 'Y',  -- 활성화 여부 (Y/N)
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES ONBOARDING_QUESTION(QUESTION_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_ONBOARDING_ANSWER
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 3. ONBOARDING_SESSION: 온보딩 세션 별 선택지 결과 항목
CREATE TABLE ONBOARDING_SESSION (
    SESSION_ID VARCHAR2(100) PRIMARY KEY,  -- 세션 ID (UUID 또는 고유 문자열)
    USER_ID VARCHAR2(100),  -- 사용자 ID (선택적, 카카오 로그인 연동 시)
    CURRENT_STEP NUMBER DEFAULT 1,  -- 현재 진행 단계 (1~6)
    STATUS VARCHAR2(20) DEFAULT 'IN_PROGRESS',  -- 상태 (IN_PROGRESS, COMPLETED, ABANDONED)
    VIBE VARCHAR2(20),  -- Step 1: 분위기
    HOUSEHOLD_SIZE NUMBER,  -- Step 2: 가구 인원수
    HAS_PET CHAR(1),  -- Step 2: 반려동물 여부 (Y/N)
    HOUSING_TYPE VARCHAR2(20),  -- Step 3: 주거 형태
    PYUNG NUMBER,  -- Step 3: 평수
    MAIN_SPACE CLOB,  -- Step 3: 주요 공간 (JSON 배열 문자열, 다중 선택)
    COOKING VARCHAR2(20),  -- Step 4: 요리 빈도
    LAUNDRY VARCHAR2(20),  -- Step 4: 세탁 빈도
    MEDIA VARCHAR2(20),  -- Step 4: 미디어 사용 패턴
    PRIORITY VARCHAR2(20),  -- Step 5: 우선순위 (첫 번째 우선순위)
    PRIORITY_LIST CLOB,  -- Step 5: 우선순위 목록 (JSON 배열 문자열, 다중 선택)
    BUDGET_LEVEL VARCHAR2(20),  -- Step 6: 예산 범위
    SELECTED_CATEGORIES CLOB,  -- 선택한 카테고리 (JSON 배열 문자열)
    RECOMMENDED_PRODUCTS CLOB,  -- 추천 제품 ID 목록 (JSON 배열 문자열)
    RECOMMENDATION_RESULT CLOB,  -- 최종 추천 결과 (JSON 객체 문자열)
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE,
    COMPLETED_AT DATE
);

-- 인덱스 생성
CREATE INDEX IDX_SESSION_USER_ID ON ONBOARDING_SESSION(USER_ID);
CREATE INDEX IDX_SESSION_STATUS ON ONBOARDING_SESSION(STATUS);
CREATE INDEX IDX_SESSION_CREATED_AT ON ONBOARDING_SESSION(CREATED_AT);

-- 4. ONBOARDING_USER_RESPONSE: 온보딩 사용자 선택지 결과 항목
CREATE TABLE ONBOARDING_USER_RESPONSE (
    RESPONSE_ID NUMBER PRIMARY KEY,
    SESSION_ID VARCHAR2(100) NOT NULL,  -- ONBOARDING_SESSION 참조
    QUESTION_ID NUMBER NOT NULL,  -- ONBOARDING_QUESTION 참조
    ANSWER_ID NUMBER,  -- ONBOARDING_ANSWER 참조 (단일 선택인 경우)
    ANSWER_VALUE VARCHAR2(200),  -- 선택한 값 (다중 선택인 경우 직접 저장)
    RESPONSE_TEXT CLOB,  -- 텍스트 입력 값 (평수 등)
    STEP_NUMBER NUMBER NOT NULL,  -- 단계 번호
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_RESPONSE_SESSION FOREIGN KEY (SESSION_ID) REFERENCES ONBOARDING_SESSION(SESSION_ID),
    CONSTRAINT FK_RESPONSE_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES ONBOARDING_QUESTION(QUESTION_ID),
    CONSTRAINT FK_RESPONSE_ANSWER FOREIGN KEY (ANSWER_ID) REFERENCES ONBOARDING_ANSWER(ANSWER_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_ONBOARDING_USER_RESPONSE
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 인덱스 생성
CREATE INDEX IDX_RESPONSE_SESSION ON ONBOARDING_USER_RESPONSE(SESSION_ID);
CREATE INDEX IDX_RESPONSE_QUESTION ON ONBOARDING_USER_RESPONSE(QUESTION_ID);
CREATE INDEX IDX_RESPONSE_STEP ON ONBOARDING_USER_RESPONSE(STEP_NUMBER);

-- ============================================================
-- 초기 데이터 삽입 (온보딩 질문 및 선택지)
-- ============================================================

-- Step 1: 분위기 질문
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 1, 'vibe', '새로운 가전과 함께할 공간, 어떤 분위기를 꿈꾸시나요?', 1, 'Y');

-- Step 1: 분위기 선택지
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'modern', '모던 & 미니멀', 1 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'vibe' AND STEP_NUMBER = 1;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'cozy', '코지 & 네이처', 2 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'vibe' AND STEP_NUMBER = 1;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'pop', '유니크 & 팝', 3 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'vibe' AND STEP_NUMBER = 1;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'luxury', '럭셔리 & 아티스틱', 4 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'vibe' AND STEP_NUMBER = 1;

-- Step 2: 메이트 질문
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 2, 'mate', '이 공간에서 함께 생활하는 메이트는 누구인가요?', 1, 'Y');

-- Step 2: 메이트 선택지
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'alone', '나 혼자 산다', 1 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'mate' AND STEP_NUMBER = 2;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'couple', '우리 둘이 알콩달콩', 2 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'mate' AND STEP_NUMBER = 2;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'family_3_4', '아이가 있는 3~4인 가족', 3 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'mate' AND STEP_NUMBER = 2;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'family_5plus', '5인 이상 대가족', 4 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'mate' AND STEP_NUMBER = 2;

-- Step 2: 반려동물 질문 (조건부)
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED, CONDITION_TYPE, CONDITION_VALUE)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 2, 'pet', '혹시 반려동물과 함께하시나요?', 2, 'Y', 'mate_selected', 'any');

-- Step 2: 반려동물 선택지
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'yes', '네, 사랑스러운 댕냥이가 있어요', 1 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'pet' AND STEP_NUMBER = 2;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'no', '아니요, 없어요', 2 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'pet' AND STEP_NUMBER = 2;

-- Step 3: 주거 형태 질문
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 3, 'housing_type', '가전을 설치할 곳의 주거 형태는 무엇인가요?', 1, 'Y');

-- Step 3: 주거 형태 선택지
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'apartment', '아파트', 1 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'housing_type' AND STEP_NUMBER = 3;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'officetel', '오피스텔', 2 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'housing_type' AND STEP_NUMBER = 3;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'detached', '주택(단독/다가구)', 3 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'housing_type' AND STEP_NUMBER = 3;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'studio', '원룸', 4 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'housing_type' AND STEP_NUMBER = 3;

-- Step 3: 주요 공간 질문 (조건부)
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED, CONDITION_TYPE, CONDITION_VALUE)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 3, 'main_space', '가전을 배치할 주요 공간은 어디인가요?', 2, 'Y', 'housing_type_selected', 'any');

-- Step 3: 주요 공간 선택지 (다중 선택 가능)
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'living', '거실', 1 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'main_space' AND STEP_NUMBER = 3;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'bedroom', '방', 2 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'main_space' AND STEP_NUMBER = 3;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'kitchen', '주방', 3 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'main_space' AND STEP_NUMBER = 3;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'dressing', '드레스룸', 4 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'main_space' AND STEP_NUMBER = 3;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'study', '서재', 5 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'main_space' AND STEP_NUMBER = 3;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'all', '전체', 6 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'main_space' AND STEP_NUMBER = 3;

-- Step 3: 평수 입력 질문 (조건부)
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED, CONDITION_TYPE, CONDITION_VALUE)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 3, 'pyung', '해당 공간의 크기는 대략 어느 정도인가요?', 3, 'Y', 'main_space_selected', 'any');

-- Step 4: 요리 질문 (조건부 - 주방 선택 시)
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED, CONDITION_TYPE, CONDITION_VALUE)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 4, 'cooking', '평소 집에서 요리는 얼마나 자주 하시나요?', 1, 'N', 'main_space_selected', 'kitchen,all');

-- Step 4: 요리 선택지
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'rarely', '거의 하지 않아요(배달, 간편식 위주)', 1 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'cooking' AND STEP_NUMBER = 4;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'sometimes', '가끔 해요(주말 위주)', 2 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'cooking' AND STEP_NUMBER = 4;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'often', '요리하는 걸 좋아하고 자주 해요', 3 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'cooking' AND STEP_NUMBER = 4;

-- Step 4: 세탁 질문 (조건부 - 드레스룸/전체 선택 시)
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED, CONDITION_TYPE, CONDITION_VALUE)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 4, 'laundry', '세탁은 주로 어떻게 하시나요?', 2, 'N', 'main_space_selected', 'dressing,all');

-- Step 4: 세탁 선택지
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'weekly', '일주일 1번 정도', 1 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'laundry' AND STEP_NUMBER = 4;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'few_times', '일주일 2번~3번 정도', 2 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'laundry' AND STEP_NUMBER = 4;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'daily', '매일 조금씩', 3 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'laundry' AND STEP_NUMBER = 4;

-- Step 4: 미디어 질문 (조건부 - 거실/방/서재 선택 시)
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED, CONDITION_TYPE, CONDITION_VALUE)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 4, 'media', '집에서 TV나 영상을 주로 어떻게 즐기시나요?', 3, 'N', 'main_space_selected', 'living,bedroom,study,all');

-- Step 4: 미디어 선택지
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'ott', '넷플릭스, 영화, 드라마 등 OTT를 즐기는 편', 1 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'media' AND STEP_NUMBER = 4;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'gaming', '게임이 취미라 주로 게임을 즐기는 편', 2 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'media' AND STEP_NUMBER = 4;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'tv', '뉴스나 예능 등 일반 프로그램 시청하는 편', 3 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'media' AND STEP_NUMBER = 4;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'none', 'TV나 영상을 즐기는 편은 아니에요', 4 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'media' AND STEP_NUMBER = 4;

-- Step 5: 우선순위 질문
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 5, 'priority', '구매 시 가장 중요하게 생각하는 것은 무엇인가요?', 1, 'Y');

-- Step 5: 우선순위 선택지 (다중 선택 가능, 순서 중요)
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'design', '디자인/무드', 1 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'priority' AND STEP_NUMBER = 5;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'tech', '기술/성능', 2 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'priority' AND STEP_NUMBER = 5;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'eco', '에너지효율', 3 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'priority' AND STEP_NUMBER = 5;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'value', '가성비', 4 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'priority' AND STEP_NUMBER = 5;

-- Step 6: 예산 질문
INSERT INTO ONBOARDING_QUESTION (QUESTION_ID, STEP_NUMBER, QUESTION_TYPE, QUESTION_TEXT, QUESTION_ORDER, IS_REQUIRED)
VALUES (SEQ_ONBOARDING_QUESTION.NEXTVAL, 6, 'budget', '예산 범위를 선택해주세요.', 1, 'Y');

-- Step 6: 예산 선택지
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'budget', '500만원 이하', 1 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'budget' AND STEP_NUMBER = 6;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'standard', '500~2000만원', 2 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'budget' AND STEP_NUMBER = 6;
INSERT INTO ONBOARDING_ANSWER (ANSWER_ID, QUESTION_ID, ANSWER_VALUE, ANSWER_TEXT, ANSWER_ORDER)
SELECT SEQ_ONBOARDING_ANSWER.NEXTVAL, QUESTION_ID, 'premium', '2000만원 이상', 3 FROM ONBOARDING_QUESTION WHERE QUESTION_TYPE = 'budget' AND STEP_NUMBER = 6;

COMMIT;

