-- PORTFOLIO 관련 테이블 생성 스크립트
-- Step 3: 포트폴리오 Oracle DB 저장 로직 구현을 위한 테이블 생성

-- 1. PORTFOLIO 테이블 생성
CREATE TABLE PORTFOLIO (
    PORTFOLIO_ID NUMBER PRIMARY KEY,
    INTERNAL_KEY VARCHAR2(20),
    USER_ID VARCHAR2(100),
    STYLE_TYPE VARCHAR2(50),
    STYLE_TITLE VARCHAR2(200),
    STYLE_SUBTITLE VARCHAR2(500),
    TOTAL_ORIGINAL_PRICE NUMBER(12, 0) DEFAULT 0,
    TOTAL_DISCOUNT_PRICE NUMBER(12, 0) DEFAULT 0,
    MATCH_SCORE NUMBER(3, 0) DEFAULT 0,
    STATUS VARCHAR2(20) DEFAULT 'draft',
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE
);

-- PORTFOLIO 테이블 인덱스
CREATE INDEX IDX_PORTFOLIO_USER_ID ON PORTFOLIO(USER_ID);
CREATE INDEX IDX_PORTFOLIO_INTERNAL_KEY ON PORTFOLIO(INTERNAL_KEY);
CREATE INDEX IDX_PORTFOLIO_STATUS ON PORTFOLIO(STATUS);

-- 2. PORTFOLIO_PRODUCT 테이블 생성
CREATE TABLE PORTFOLIO_PRODUCT (
    ID NUMBER PRIMARY KEY,
    PORTFOLIO_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    PRIORITY NUMBER DEFAULT 1,
    RECOMMEND_REASON VARCHAR2(500),
    CONSTRAINT FK_PORTFOLIO_PRODUCT_PORTFOLIO 
        FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO(PORTFOLIO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PORTFOLIO_PRODUCT_PRODUCT 
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE
);

-- PORTFOLIO_PRODUCT 테이블 인덱스
CREATE INDEX IDX_PORTFOLIO_PRODUCT_PORTFOLIO_ID ON PORTFOLIO_PRODUCT(PORTFOLIO_ID);
CREATE INDEX IDX_PORTFOLIO_PRODUCT_PRODUCT_ID ON PORTFOLIO_PRODUCT(PRODUCT_ID);
CREATE INDEX IDX_PORTFOLIO_PRODUCT_PRIORITY ON PORTFOLIO_PRODUCT(PORTFOLIO_ID, PRIORITY);

-- 3. PORTFOLIO_SESSION 테이블 생성
CREATE TABLE PORTFOLIO_SESSION (
    PORTFOLIO_ID NUMBER PRIMARY KEY,
    SESSION_ID VARCHAR2(100) NOT NULL,
    MEMBER_ID VARCHAR2(100),
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PORTFOLIO_SESSION_PORTFOLIO 
        FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO(PORTFOLIO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PORTFOLIO_SESSION_SESSION 
        FOREIGN KEY (SESSION_ID) REFERENCES ONBOARDING_SESSION(SESSION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PORTFOLIO_SESSION_MEMBER 
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE SET NULL
);

-- PORTFOLIO_SESSION 테이블 인덱스
CREATE INDEX IDX_PORTFOLIO_SESSION_SESSION_ID ON PORTFOLIO_SESSION(SESSION_ID);
CREATE INDEX IDX_PORTFOLIO_SESSION_MEMBER_ID ON PORTFOLIO_SESSION(MEMBER_ID);

-- 4. PORTFOLIO_ID 시퀀스 생성 (선택적)
CREATE SEQUENCE SEQ_PORTFOLIO_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 5. PORTFOLIO_PRODUCT ID 시퀀스 생성 (선택적)
CREATE SEQUENCE SEQ_PORTFOLIO_PRODUCT_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 테이블 코멘트 추가
COMMENT ON TABLE PORTFOLIO IS '포트폴리오 기본 정보 테이블';
COMMENT ON COLUMN PORTFOLIO.PORTFOLIO_ID IS '포트폴리오 ID (PRIMARY KEY)';
COMMENT ON COLUMN PORTFOLIO.INTERNAL_KEY IS '포트폴리오 내부 키';
COMMENT ON COLUMN PORTFOLIO.USER_ID IS '사용자 ID';
COMMENT ON COLUMN PORTFOLIO.STYLE_TYPE IS '스타일 타입 (modern, cozy, natural, luxury)';
COMMENT ON COLUMN PORTFOLIO.STYLE_TITLE IS '스타일 타이틀';
COMMENT ON COLUMN PORTFOLIO.STYLE_SUBTITLE IS '스타일 서브타이틀';
COMMENT ON COLUMN PORTFOLIO.TOTAL_ORIGINAL_PRICE IS '정가 합계';
COMMENT ON COLUMN PORTFOLIO.TOTAL_DISCOUNT_PRICE IS '할인가 합계';
COMMENT ON COLUMN PORTFOLIO.MATCH_SCORE IS '매칭 점수 (0-100)';
COMMENT ON COLUMN PORTFOLIO.STATUS IS '포트폴리오 상태 (draft, saved, shared, purchased)';

COMMENT ON TABLE PORTFOLIO_PRODUCT IS '포트폴리오 제품 목록 테이블';
COMMENT ON COLUMN PORTFOLIO_PRODUCT.ID IS '포트폴리오 제품 ID (PRIMARY KEY)';
COMMENT ON COLUMN PORTFOLIO_PRODUCT.PORTFOLIO_ID IS '포트폴리오 ID (FK)';
COMMENT ON COLUMN PORTFOLIO_PRODUCT.PRODUCT_ID IS '제품 ID (FK)';
COMMENT ON COLUMN PORTFOLIO_PRODUCT.PRIORITY IS '우선순위 (순위)';
COMMENT ON COLUMN PORTFOLIO_PRODUCT.RECOMMEND_REASON IS '추천 이유';

COMMENT ON TABLE PORTFOLIO_SESSION IS '포트폴리오-세션 연결 테이블';
COMMENT ON COLUMN PORTFOLIO_SESSION.PORTFOLIO_ID IS '포트폴리오 ID (PRIMARY KEY, FK)';
COMMENT ON COLUMN PORTFOLIO_SESSION.SESSION_ID IS '세션 ID (FK)';
COMMENT ON COLUMN PORTFOLIO_SESSION.MEMBER_ID IS '회원 ID (FK)';

