# Generated by Django 5.2.8 on 2025-11-28 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('household_size', models.CharField(blank=True, max_length=20)),
                ('space_type', models.CharField(blank=True, max_length=20)),
                ('space_purpose', models.CharField(blank=True, max_length=50)),
                ('space_sqm', models.FloatField(blank=True, null=True)),
                ('space_size_cat', models.CharField(blank=True, max_length=20)),
                ('style_pref', models.CharField(blank=True, max_length=50)),
                ('cooking_freq', models.CharField(blank=True, max_length=20)),
                ('laundry_pattern', models.CharField(blank=True, max_length=50)),
                ('media_pref', models.CharField(blank=True, max_length=50)),
                ('pet', models.CharField(blank=True, max_length=10)),
                ('budget_range', models.CharField(blank=True, max_length=50)),
                ('payment_pref', models.CharField(blank=True, max_length=20)),
                ('recommended_fridge_l', models.IntegerField(blank=True, null=True)),
                ('recommended_washer_kg', models.IntegerField(blank=True, null=True)),
                ('recommended_tv_inch', models.IntegerField(blank=True, null=True)),
                ('recommended_vacuum', models.CharField(blank=True, max_length=50)),
                ('recommended_oven', models.CharField(blank=True, max_length=50)),
                ('purchased_items', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '사용자 샘플',
                'verbose_name_plural': '사용자 샘플',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('spec_json', models.TextField(blank=True, default='{}')),
                ('ingested_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='api.product')),
            ],
        ),
    ]
