# Generated by Django 5.2.8 on 2025-11-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersample_productspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersample',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
