# Generated by Django 4.2.16 on 2025-12-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fix_model_mismatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioVersion',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('change_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portfolio_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('link_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('share_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'share_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StyleMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('vibe', models.CharField(max_length=20)),
                ('household_size', models.IntegerField(blank=True, null=True)),
                ('budget_level', models.CharField(blank=True, max_length=20, null=True)),
                ('title_text', models.CharField(max_length=500)),
                ('subtitle_text', models.CharField(max_length=1000)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'style_message',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='onboardingsession',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': '온보딩 세션', 'verbose_name_plural': '온보딩 세션'},
        ),
    ]
