# Generated by Django 4.2.16 on 2025-12-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_portfolioversion_sharelink_stylemessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingsession',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': '온보딩 세션', 'verbose_name_plural': '온보딩 세션'},
        ),
    ]
