# Generated by Django 4.2.16 on 2025-12-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_onboardingsession_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onboardingsession',
            new_name='onboarding__session_e2db14_idx',
            old_name='api_onboard_session_e76c26_idx',
        ),
        migrations.RenameIndex(
            model_name='onboardingsession',
            new_name='onboarding__status_ed4976_idx',
            old_name='api_onboard_status_38b560_idx',
        ),
        migrations.RenameIndex(
            model_name='onboardingsession',
            new_name='onboarding__created_542130_idx',
            old_name='api_onboard_created_b0a973_idx',
        ),
        migrations.AlterModelTable(
            name='onboardingsession',
            table='onboarding_session',
        ),
    ]
