# Generated by Django 5.2.8 on 2025-12-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_specs_alter_usersample_user_id'),
        ('api', '0006_add_portfolio_model'),
    ]

    operations = [
    ]
