# Generated by Django 4.2.16 on 2025-12-10 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_onboardingsession_recommendation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsession',
            name='taste_id',
            field=models.IntegerField(blank=True, help_text='매칭된 Taste ID (1-1920, TASTE_CONFIG와 비교하여 설정)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1920)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='taste',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='할당된 Taste ID'),
        ),
    ]
