# Generated by Django 4.2.16 on 2025-12-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_onboardingsession_taste_id_alter_member_taste'),
    ]

    operations = [
        # OnboardingSessionCategories: id 필드 추가 및 primary_key 제거
        migrations.AddField(
            model_name='onboardingsessioncategories',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onboardingsessioncategories',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='session_categories', to='api.onboardingsession', verbose_name='세션'),
        ),
        # OnboardingSessionMainSpaces: id 필드 추가 및 primary_key 제거
        migrations.AddField(
            model_name='onboardingsessionmainspaces',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onboardingsessionmainspaces',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='session_main_spaces', to='api.onboardingsession', verbose_name='세션'),
        ),
        # OnboardSessCategories: id 필드 추가 및 primary_key 제거
        migrations.AddField(
            model_name='onboardsesscategories',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onboardsesscategories',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='onboard_sess_categories', to='api.onboardingsession'),
        ),
        # OnboardSessMainSpaces: id 필드 추가 및 primary_key 제거
        migrations.AddField(
            model_name='onboardsessmainspaces',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onboardsessmainspaces',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='onboard_sess_main_spaces', to='api.onboardingsession'),
        ),
    ]
