# Generated by Django 5.2.8 on 2025-12-04 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20251204_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='internal_key',
            field=models.CharField(blank=True, db_index=True, help_text='포트폴리오 내부 키 (UUID 또는 P001, P002 형식)', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='사용자 ID (카카오 ID 또는 세션 ID)', max_length=100)),
                ('quantity', models.IntegerField(default=1, help_text='제품 수량')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='추가 정보 (가격, 할인 정보 등)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='장바구니에 담긴 제품', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.product')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='api_cart_user_id_be156f_idx'), models.Index(fields=['product'], name='api_cart_product_b4719c_idx')],
                'unique_together': {('user_id', 'product')},
            },
        ),
    ]
