# Generated by Django 4.2.17 on 2025-12-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_product_specs_portfolio_internal_key_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasteConfig',
            fields=[
                ('taste_id', models.IntegerField(help_text='Taste ID (1-120)', primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, help_text='Taste 설명', max_length=500)),
                ('representative_vibe', models.CharField(blank=True, max_length=20)),
                ('representative_household_size', models.IntegerField(blank=True, null=True)),
                ('representative_main_space', models.CharField(blank=True, max_length=50)),
                ('representative_has_pet', models.BooleanField(blank=True, null=True)),
                ('representative_priority', models.CharField(blank=True, max_length=20)),
                ('representative_budget_level', models.CharField(blank=True, max_length=20)),
                ('recommended_categories', models.JSONField(default=list, help_text="추천 MAIN_CATEGORY 리스트 (예: ['TV', '냉장고', '에어컨'])")),
                ('recommended_products', models.JSONField(default=dict, help_text='카테고리별 추천 제품 ID 매핑')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('auto_generated', models.BooleanField(default=False, help_text='자동 생성 여부')),
                ('last_simulation_date', models.DateTimeField(blank=True, help_text='마지막 시뮬레이션 실행일', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taste 설정',
                'verbose_name_plural': 'Taste 설정',
                'ordering': ['taste_id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='api_cart_user_id_be156f_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='api_cart_product_b4719c_idx',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='internal_key',
        ),
        migrations.AlterField(
            model_name='cart',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
