# Generated by Django 4.2.17 on 2025-12-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tasteconfig_remove_cart_api_cart_user_id_be156f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasteconfig',
            name='ill_suited_categories',
            field=models.JSONField(blank=True, default=list, help_text='Ill-suited 카테고리 리스트 (온보딩 답변과 완전히 부적합한 카테고리)'),
        ),
        migrations.AddField(
            model_name='tasteconfig',
            name='recommended_categories_with_scores',
            field=models.JSONField(blank=True, default=dict, help_text='카테고리별 점수 매핑 (0~100점)'),
        ),
    ]
