# Generated by Django 4.2.17 on 2025-12-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wishlist'),
        ('api', '0011_add_portfolio_internal_key'),
    ]

    operations = [
    ]
