# Generated by Django 4.2.17 on 2025-12-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_0005_wishlist_0011_add_portfolio_internal_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portfolio',
            new_name='api_portfol_interna_1954c7_idx',
            old_name='api_portfol_interna_idx',
        ),
    ]
