# Generated by Django 4.2.17 on 2025-12-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_api_portfol_interna_idx_api_portfol_interna_1954c7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(help_text='예약 ID (예: BS-PF-XXXXXX-TIMESTAMP)', max_length=50, unique=True)),
                ('user_id', models.CharField(db_index=True, help_text='사용자 ID (카카오 ID 또는 세션 ID)', max_length=100)),
                ('consultation_purpose', models.CharField(default='이사', help_text='상담 목적 (이사, 신혼, 리모델링 등)', max_length=100)),
                ('preferred_date', models.DateField(blank=True, help_text='희망 날짜', null=True)),
                ('preferred_time', models.TimeField(blank=True, help_text='희망 시간', null=True)),
                ('store_location', models.CharField(blank=True, help_text='매장 위치 (예: 서울 강남점)', max_length=200)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('confirmed', '확정됨'), ('completed', '완료됨'), ('cancelled', '취소됨')], default='pending', help_text='예약 상태', max_length=20)),
                ('contact_name', models.CharField(blank=True, help_text='연락처 이름', max_length=100)),
                ('contact_phone', models.CharField(blank=True, help_text='연락처 전화번호', max_length=20)),
                ('contact_email', models.EmailField(blank=True, help_text='연락처 이메일', max_length=254)),
                ('memo', models.TextField(blank=True, help_text='추가 메모')),
                ('external_reservation_id', models.CharField(blank=True, help_text='베스트샵 시스템 예약 ID (외부 시스템 연동 시)', max_length=100)),
                ('external_system_url', models.URLField(blank=True, help_text='외부 시스템 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(blank=True, help_text='연결된 포트폴리오', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='api.portfolio')),
            ],
            options={
                'verbose_name': '상담 예약',
                'verbose_name_plural': '상담 예약',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='api_reserva_user_id_603e5f_idx'), models.Index(fields=['reservation_id'], name='api_reserva_reserva_c9067b_idx'), models.Index(fields=['status'], name='api_reserva_status_b87e2f_idx'), models.Index(fields=['preferred_date'], name='api_reserva_preferr_b56323_idx')],
            },
        ),
    ]
