# Generated by Django 5.2.8 on 2025-11-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제품명')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='모델명')),
                ('category', models.CharField(choices=[('TV', 'TV/오디오'), ('KITCHEN', '주방가전'), ('LIVING', '생활가전'), ('AIR', '에어컨/에어케어'), ('AI', 'AI Home'), ('OBJET', 'LG Objet'), ('SIGNATURE', 'LG SIGNATURE')], max_length=20, verbose_name='카테고리')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='가격')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='할인가')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='판매중')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'ordering': ['-created_at'],
            },
        ),
    ]
