# Generated by Django 5.2.8 on 2025-11-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usersample_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='고유 세션 ID', max_length=100, unique=True)),
                ('vibe', models.CharField(blank=True, choices=[('modern', '모던/심플'), ('cozy', '따뜻한 톤'), ('pop', '팝/생기있는'), ('luxury', '럭셔리/고급')], help_text='Step 1: 인테리어 무드', max_length=20, null=True)),
                ('household_size', models.IntegerField(blank=True, help_text='Step 2: 가구 인원수', null=True)),
                ('housing_type', models.CharField(blank=True, choices=[('apartment', '아파트'), ('detached', '단독주택'), ('villa', '빌라/연립'), ('officetel', '오피스텔'), ('studio', '원룸')], help_text='Step 3: 주거 형태', max_length=20, null=True)),
                ('pyung', models.IntegerField(blank=True, help_text='Step 3: 주거 평수', null=True)),
                ('priority', models.CharField(choices=[('design', '디자인/무드'), ('tech', '기술/성능'), ('eco', '에너지효율'), ('value', '가성비')], default='value', help_text='Step 4: 구매 우선순위', max_length=20)),
                ('budget_level', models.CharField(choices=[('low', '500만원 이하'), ('medium', '500~2000만원'), ('high', '2000만원 이상'), ('budget', '500만원 이하'), ('standard', '500~2000만원'), ('premium', '2000만원 이상'), ('luxury', '2000만원 이상')], default='medium', help_text='Step 5: 예산 범위', max_length=20)),
                ('selected_categories', models.JSONField(default=list, help_text="선택한 제품 카테고리 (예: ['TV', 'KITCHEN'])")),
                ('recommended_products', models.JSONField(default=list, help_text='추천 제품 ID 목록')),
                ('recommendation_result', models.JSONField(default=dict, help_text='최종 추천 결과 (JSON)')),
                ('current_step', models.IntegerField(choices=[(1, 'Step 1'), (2, 'Step 2'), (3, 'Step 3'), (4, 'Step 4'), (5, 'Step 5'), (6, 'Step 6')], default=1, help_text='현재 진행 중인 스텝')),
                ('status', models.CharField(choices=[('in_progress', '진행중'), ('completed', '완료'), ('abandoned', '중단됨')], default='in_progress', help_text='온보딩 상태', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='세션 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='마지막 업데이트 시간')),
                ('completed_at', models.DateTimeField(blank=True, help_text='온보딩 완료 시간', null=True)),
            ],
            options={
                'verbose_name': '온보딩 세션',
                'verbose_name_plural': '온보딩 세션',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='api_onboard_session_e76c26_idx'), models.Index(fields=['status'], name='api_onboard_status_38b560_idx'), models.Index(fields=['created_at'], name='api_onboard_created_b0a973_idx')],
            },
        ),
    ]
