# Generated by Django 4.2.17 on 2025-11-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productspec_options_productreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(help_text='포트폴리오 내부 키 (예: PF-001, PF-002)', max_length=20, unique=True)),
                ('user_id', models.CharField(db_index=True, help_text='사용자 ID (카카오 ID 또는 세션 ID)', max_length=100)),
                ('style_type', models.CharField(choices=[('modern', '모던 & 미니멀'), ('cozy', '따뜻한 코지'), ('natural', '내추럴 & 네이처'), ('luxury', '럭셔리 & 프리미엄')], default='modern', help_text='스타일 유형', max_length=50)),
                ('style_title', models.CharField(blank=True, help_text='스타일 타이틀 (예: 모던 & 미니멀 라이프를 위한 오브제 스타일)', max_length=200)),
                ('style_subtitle', models.TextField(blank=True, help_text='스타일 설명 (ChatGPT 생성 가능)')),
                ('onboarding_data', models.JSONField(default=dict, help_text='온보딩 설문 응답 데이터')),
                ('products', models.JSONField(default=list, help_text='추천 제품 목록 [{id, name, price, ...}, ...]')),
                ('total_original_price', models.DecimalField(decimal_places=0, default=0, help_text='정가 합계', max_digits=12)),
                ('total_discount_price', models.DecimalField(decimal_places=0, default=0, help_text='할인가 합계', max_digits=12)),
                ('match_score', models.IntegerField(default=0, help_text='전체 매칭 점수 (0-100)')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('saved', '저장됨'), ('shared', '공유됨'), ('purchased', '구매완료')], default='draft', help_text='포트폴리오 상태', max_length=20)),
                ('share_url', models.CharField(blank=True, help_text='공유 URL', max_length=200)),
                ('share_count', models.IntegerField(default=0, help_text='공유 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding_session', models.ForeignKey(blank=True, help_text='연결된 온보딩 세션', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='api.onboardingsession')),
            ],
            options={
                'verbose_name': '포트폴리오',
                'verbose_name_plural': '포트폴리오',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='api_portfol_user_id_e5189f_idx'), models.Index(fields=['portfolio_id'], name='api_portfol_portfol_9fb3c2_idx'), models.Index(fields=['status'], name='api_portfol_status_17b537_idx')],
            },
        ),
    ]
