# Generated by Django 4.2.17 on 2025-11-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_onboardingsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspec',
            options={'verbose_name': '제품 스펙', 'verbose_name_plural': '제품 스펙'},
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(blank=True, default='', max_length=20)),
                ('review_text', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.product')),
            ],
            options={
                'verbose_name': '제품 리뷰',
                'verbose_name_plural': '제품 리뷰',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_reason', to='api.product')),
            ],
            options={
                'verbose_name': '제품 추천이유',
                'verbose_name_plural': '제품 추천이유',
            },
        ),
        migrations.CreateModel(
            name='ProductDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_types', models.JSONField(blank=True, default=list)),
                ('house_sizes', models.JSONField(blank=True, default=list)),
                ('house_types', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='api.product')),
            ],
            options={
                'verbose_name': '제품 인구통계',
                'verbose_name_plural': '제품 인구통계',
            },
        ),
    ]
