"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# 환경 변수 로드 (.env 파일)
# ============================================================
try:
    from dotenv import load_dotenv
    # 프로젝트 루트 디렉토리의 .env 파일 로드
    env_path = Path(__file__).resolve().parent.parent / '.env'
    load_dotenv(dotenv_path=env_path)
    print(f"[ENV] .env 파일 로드 완료: {env_path}")
except ImportError:
    print("[WARNING] python-dotenv가 설치되지 않았습니다. pip install python-dotenv 실행하세요.")
except Exception as e:
    print(f"[WARNING] .env 파일 로드 실패: {e}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-8zb-1$0d6^f=&c@v8-l2-9b*9ydnp7k3m0-s_y8gljjkvtiyt8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# ============================================================
# 외부 API 키 설정
# ============================================================

# 카카오 API (https://developers.kakao.com)
KAKAO_REST_API_KEY = os.environ.get('KAKAO_REST_API_KEY', '')
KAKAO_JS_KEY = os.environ.get('KAKAO_JS_KEY', '')

# OpenAI API (https://platform.openai.com) - ChatGPT 연동용
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# API 키 설정 확인 (디버그 모드에서만)
if DEBUG:
    print(f"[API Keys Status]")
    print(f"  KAKAO_JS_KEY: {'[OK] 설정됨' if KAKAO_JS_KEY else '[X] 미설정'}")
    print(f"  OPENAI_API_KEY: {'[OK] 설정됨' if OPENAI_API_KEY else '[X] 미설정'}")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
    }
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Oracle 데이터베이스 설정
# 커스텀 백엔드를 사용하여 Oracle 11g 지원 (버전 체크 우회)

# 환경 변수에서 Oracle 설정 로드
db_host = os.environ.get('ORACLE_HOST') or os.environ.get('DB_HOST', 'project-db-campus.smhrd.com')
db_port = os.environ.get('ORACLE_PORT') or os.environ.get('DB_PORT', '1524')
db_sid = os.environ.get('ORACLE_SID', 'xe')  # SQL Developer에서 확인한 SID
db_user = os.environ.get('ORACLE_USER') or os.environ.get('DB_USER', '')
db_password = os.environ.get('ORACLE_PASSWORD') or os.environ.get('DB_PASSWORD', '')

DATABASES = {
    'default': {
        'ENGINE': 'api.db.oracle_backend',  # 커스텀 백엔드 (Oracle 11g 버전 체크 우회)
        'HOST': db_host,
        'PORT': db_port,
        'NAME': db_sid,  # SID: xe
        'USER': db_user,
        'PASSWORD': db_password,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# Django REST Framework 설정
# ============================================================
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # 브라우저 API 테스트 UI
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}