"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# 환경 변수 로드 (.env 파일)
# ============================================================
try:
    from dotenv import dotenv_values
    # 프로젝트 루트 디렉토리의 .env 파일 로드
    env_path = Path(__file__).resolve().parent.parent / '.env'
    if env_path.exists():
        try:
            # UTF-8로 시도
            with open(env_path, 'r', encoding='utf-8') as f:
                env_vars = dotenv_values(stream=f)
                for key, value in env_vars.items():
                    if value is not None:
                        os.environ.setdefault(key, value)
            print(f"[ENV] .env 파일 로드 완료: {env_path}")
        except UnicodeDecodeError:
            # UTF-8 실패 시 CP949 (Windows 기본 인코딩)로 시도
            try:
                with open(env_path, 'r', encoding='cp949') as f:
                    env_vars = dotenv_values(stream=f)
                    for key, value in env_vars.items():
                        if value is not None:
                            os.environ.setdefault(key, value)
                print(f"[ENV] .env 파일 로드 완료 (CP949): {env_path}")
            except Exception as e:
                print(f"[WARNING] .env 파일 로드 실패 (CP949): {e}")
        except Exception as e:
            print(f"[WARNING] .env 파일 로드 실패: {e}")
    else:
        print(f"[WARNING] .env 파일을 찾을 수 없습니다: {env_path}")
except ImportError:
    print("[WARNING] python-dotenv가 설치되지 않았습니다. pip install python-dotenv 실행하세요.")
except Exception as e:
    print(f"[WARNING] .env 파일 로드 실패: {e}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# PRD 개선: 프로덕션에서는 기본값 False (보안 강화)
# DEBUG를 먼저 정의해야 SECRET_KEY에서 사용 가능
# 개발 환경에서는 기본값 True (환경 변수로 명시적으로 False 설정하지 않는 한)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# PRD 개선: 프로덕션에서는 환경 변수 필수
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # 개발 환경만 기본값 허용
        SECRET_KEY = 'django-insecure-8zb-1$0d6^f=&c@v8-l2-9b*9ydnp7k3m0-s_y8gljjkvtiyt8'
        print("[WARNING] SECRET_KEY 기본값 사용 중 (개발 환경). 프로덕션에서는 DJANGO_SECRET_KEY 환경 변수를 설정하세요.")
    else:
        raise ValueError("DJANGO_SECRET_KEY 환경 변수가 설정되지 않았습니다. 프로덕션에서는 필수입니다.")

# ALLOWED_HOSTS: 환경 변수로 제어 (쉼표로 구분, 기본값: localhost,127.0.0.1)
# 프로덕션에서는 환경 변수에 도메인을 설정: ALLOWED_HOSTS=your-app.railway.app,yourdomain.com
# PRD 개선: ngrok 도메인은 환경 변수로 관리
default_hosts = 'localhost,127.0.0.1,testserver'
# 기본 ngrok 도메인 추가 (환경 변수로 오버라이드 가능)
default_hosts += ',braeden-unaromatic-zola.ngrok-free.dev'
# ngrok-free.app 도메인 패턴 허용 (무료 계정용)
default_hosts += ',*.ngrok-free.app,*.ngrok.app,*.ngrok.io'
ngrok_host = os.environ.get('NGROK_HOST')
if ngrok_host:
    default_hosts += f',{ngrok_host}'
allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', default_hosts)
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]

# CSRF 설정 (React 앱에서 API 호출 허용)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://braeden-unaromatic-zola.ngrok-free.dev',  # NGROK URL
]
# 환경 변수로 추가 도메인 설정 가능
csrf_origins_str = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins_str:
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in csrf_origins_str.split(',') if origin.strip()])

# CORS 설정
# 프로덕션에서는 환경 변수로 설정
cors_origins_str = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if cors_origins_str:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_str.split(',') if origin.strip()]
else:
    # 개발 환경 기본값
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
CORS_ALLOW_CREDENTIALS = True

# 프로덕션 환경에서 CORS 허용 (필요시)
if not DEBUG:
    CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'false').lower() == 'true'

# ============================================================
# 외부 API 키 설정
# ============================================================

# 카카오 API (https://developers.kakao.com)
KAKAO_REST_API_KEY = os.environ.get('KAKAO_REST_API_KEY', '')
KAKAO_JS_KEY = os.environ.get('KAKAO_JS_KEY', '')
KAKAO_NATIVE_APP_KEY = os.environ.get('KAKAO_NATIVE_APP_KEY', '')
KAKAO_ADMIN_KEY = os.environ.get('KAKAO_ADMIN_KEY', '')

# OpenAI API (https://platform.openai.com) - ChatGPT 연동용
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# API 키 설정 확인 (디버그 모드에서만)
if DEBUG:
    print(f"[API Keys Status]")
    print(f"  KAKAO_REST_API_KEY: {'[OK] 설정됨' if KAKAO_REST_API_KEY else '[X] 미설정'}")
    print(f"  KAKAO_JS_KEY: {'[OK] 설정됨' if KAKAO_JS_KEY else '[X] 미설정'}")
    print(f"  KAKAO_NATIVE_APP_KEY: {'[OK] 설정됨' if KAKAO_NATIVE_APP_KEY else '[X] 미설정'}")
    print(f"  KAKAO_ADMIN_KEY: {'[OK] 설정됨' if KAKAO_ADMIN_KEY else '[X] 미설정'}")
    print(f"  OPENAI_API_KEY: {'[OK] 설정됨' if OPENAI_API_KEY else '[X] 미설정'}")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 정적 파일 서빙 (프로덕션)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS 미들웨어 (개발 환경용 - django-cors-headers 없이도 작동하도록)
# 프로덕션에서는 django-cors-headers 설치 권장: pip install django-cors-headers
try:
    import corsheaders
    MIDDLEWARE.insert(1, 'corsheaders.middleware.CorsMiddleware')
    INSTALLED_APPS.append('corsheaders')
except ImportError:
    # django-cors-headers가 없으면 수동 CORS 헤더 추가 (개발 환경용)
    pass

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
    }
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ============================================================
# Oracle 11g XE 데이터베이스 설정 (Thick 모드)
# ============================================================
# 데이터베이스 설정
# USE_ORACLE 환경변수가 'true'이면 Oracle, 아니면 SQLite 사용
# DISABLE_DB 환경변수가 'true'이면 DB 연결 없이 실행 (DB 사용 API는 에러 반환)
USE_ORACLE = os.environ.get('USE_ORACLE', 'false').lower() == 'true'
DISABLE_DB = os.environ.get('DISABLE_DB', 'false').lower() == 'true'

if DISABLE_DB:
    # DB 연결 비활성화 모드: SQLite를 설정하지만 실제로는 연결하지 않음
    # Django 서버는 시작되지만 DB를 사용하는 API는 에러를 반환함
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',  # 메모리 DB로 설정 (실제 사용 안함)
        }
    }
    print("⚠️ [DB] DB 연결이 비활성화되었습니다. (DISABLE_DB=true)")
    print("   DB를 사용하는 API는 에러를 반환할 수 있습니다.")
elif USE_ORACLE:
    # Oracle Instant Client 경로 설정
    ORACLE_INSTANT_CLIENT_PATH = os.environ.get(
        'ORACLE_INSTANT_CLIENT_PATH',
        r'C:\oracle\instantclient-basic-windows.x64-21.19.0.0.0dbru\instantclient_21_19'
    )
    
    # Oracle Thick 모드 초기화 (Oracle 11g XE는 Thick 모드 필수)
    import oracledb
    try:
        oracledb.init_oracle_client(lib_dir=ORACLE_INSTANT_CLIENT_PATH)
    except oracledb.ProgrammingError:
        # 이미 초기화된 경우 무시
        pass
    except Exception as e:
        print(f"⚠️ Oracle Instant Client 초기화 실패: {e}")
        print(f"   경로 확인: {ORACLE_INSTANT_CLIENT_PATH}")
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.oracle',
            'NAME': os.environ.get('ORACLE_SID', 'xe'),  # Oracle SID
            'USER': os.environ.get('ORACLE_USER', 'system'),
            'PASSWORD': os.environ.get('ORACLE_PASSWORD', ''),
            'HOST': os.environ.get('ORACLE_HOST', 'localhost'),
            'PORT': os.environ.get('ORACLE_PORT', '1521'),
            # DB 연결 실패 시에도 서버 시작 허용
            'OPTIONS': {
                'connect_timeout': 5,  # 연결 타임아웃 5초
            },
        }
    }
    # DB 연결 실패를 허용하는 설정 추가
    # Django는 기본적으로 서버 시작 시 DB 연결을 확인하지 않음 (지연 연결)
else:
    # 개발용 SQLite (Oracle 없이 테스트 시 사용)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

# React 빌드 결과물을 정적 파일로 포함
if (BASE_DIR / 'staticfiles' / 'react').exists():
    STATICFILES_DIRS.append(BASE_DIR / 'staticfiles' / 'react')

# 프로덕션 환경에서 정적 파일 수집 디렉토리
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise 설정 (프로덕션 환경에서 정적 파일 서빙)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise 추가 설정
WHITENOISE_ROOT = BASE_DIR / 'staticfiles' / 'react'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# 로깅 설정
# ============================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# 로그 디렉토리 생성
log_dir = BASE_DIR / 'logs'
if not log_dir.exists():
    log_dir.mkdir(exist_ok=True)

# ============================================================
# Django REST Framework 설정
# ============================================================
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] + (['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []),  # 프로덕션에서는 비활성화
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# ============================================================
# 보안 설정 (프로덕션)
# ============================================================
if not DEBUG:
    # HTTPS 강제 (프로덕션)
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'false').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'