# Generated by Django 5.2.8 on 2025-11-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersample_productspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, verbose_name='제품 스펙'),
        ),
        migrations.AlterField(
            model_name='usersample',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
